{{ $API := "api-gateway" }}
{{ if (index .Values.services $API).ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-petclinic-api-gateway-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ (index .Values.services $API).ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spring-petclinic-api-gateway
            port:
              number: {{ (index .Values.services $API).port }}
{{ end }}