{{- if and $config.ingress $config.ingress.enabled }}
---apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-petclinic-api-gateway-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.services.api-gateway.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-petclinic-api-gateway
                port:
                  number: {{ .Values.services.api-gateway.port }}
{{- end }}
