namespace: petclinic-dev
services:
  config-server:
    image: chitaialm/petclinic
    tagname: spring-petclinic-config-server
    port: 8888
  customers-service:
    image: chitaialm/petclinic
    tagname: spring-petclinic-customers-service
    port: 8081
  discovery-server:
    image: chitaialm/petclinic
    tagname: spring-petclinic-discovery-server
    port: 8761
  visits-service:
    image: chitaialm/petclinic
    tagname: spring-petclinic-visits-service
    port: 8082
  vets-service:
    image: chitaialm/petclinic
    tagname: spring-petclinic-vets-service
    port: 8083
  genai-service:
    image: chitaialm/petclinic
    tagname: spring-petclinic-genai-service
    port: 8084
  api-gateway:
    image: chitaialm/petclinic
    tagname: spring-petclinic-api-gateway
    port: 8080
    ingress:
      enabled: true
      host: petclinic-dev.tech
  admin-server:
    image: chitaialm/petclinic
    tagname: spring-petclinic-admin-server
    port: 9090
  tracing-server:
    name: tracing-server
    image: chitaialm/petclinic
    tagname: tracing
    tag: main
    port: 9411
replicaCount: 1