namespace: ${NAMESPACE}
services:
  config-server:
    image: ${DOCKER_REGISTRY}
    tag: spring-petclinic-config-server-${CONFIG_SERVER_TAG}
    port: 8888
  customers-service:
    image: ${DOCKER_REGISTRY}
    tag: spring-petclinic-customers-service-${CUSTOMERS_SERVICE_TAG}
    port: 8081
  discovery-server:
    image: ${DOCKER_REGISTRY}
    tag: spring-petclinic-discovery-server-${DISCOVERY_SERVER_TAG}
    port: 8761
  visits-service:
    image: ${DOCKER_REGISTRY}
    tag: spring-petclinic-visits-service-${VISITS_SERVICE_TAG}
    port: 8082
  vets-service:
    image: ${DOCKER_REGISTRY}
    tag: spring-petclinic-vets-service-${VETS_SERVICE_TAG}
    port: 8083
  genai-service:
    image: ${DOCKER_REGISTRY}
    tag: spring-petclinic-genai-service-${GENAI_SERVICE_TAG}
    port: 8084
  api-gateway:
    image: ${DOCKER_REGISTRY}
    tag: spring-petclinic-api-gateway-${API_GATEWAY_TAG}
    port: 8080
    ingress:
      enabled: true
      host: petclinic-dev.tech
  admin-server:
    image: ${DOCKER_REGISTRY}
    tag: spring-petclinic-admin-server-${ADMIN_SERVER_TAG}
    port: 9090
replicaCount: 1
