namespace: petclinic-dev
services:
  config-server:
    image: chitaialm/petclinic
    tag: spring-petclinic-config-server-main
    port: 8888
  customers-service:
    image: chitaialm/petclinic
    tag: spring-petclinic-customers-service-main
    port: 8081
  discovery-server:
    image: chitaialm/petclinic
    tag: spring-petclinic-discovery-server-main
    port: 8761
  visits-service:
    image: chitaialm/petclinic
    tag: spring-petclinic-visits-service-main
    port: 8082
  vets-service:
    image: chitaialm/petclinic
    tag: spring-petclinic-vets-service-main
    port: 8083
  genai-service:
    image: chitaialm/petclinic
    tag: spring-petclinic-genai-service-main
    port: 8084
  api-gateway:
    image: chitaialm/petclinic
    tag: spring-petclinic-api-gateway-main
    port: 8080
    ingress:
      enabled: true
      host: petclinic-dev1.tech
  admin-server:
    image: chitaialm/petclinic
    tag: spring-petclinic-admin-server-main
    port: 9090
replicaCount: 1