namespace: "{{ .Values.namespace }}"
services:
  config-server:
    image: "{{ .Values.dockerRegistry }}"
    tag: "spring-petclinic-config-server-{{ .Values.services.config-server.tag }}"
    port: 8888
  customers-service:
    image: "{{ .Values.dockerRegistry }}"
    tag: "spring-petclinic-customers-service-{{ .Values.services.customers-service.tag }}"
    port: 8081
  discovery-server:
    image: "{{ .Values.dockerRegistry }}"
    tag: "spring-petclinic-discovery-server-{{ .Values.services.discovery-server.tag }}"
    port: 8761
  visits-service:
    image: "{{ .Values.dockerRegistry }}"
    tag: "spring-petclinic-visits-service-{{ .Values.services.visits-service.tag }}"
    port: 8082
  vets-service:
    image: "{{ .Values.dockerRegistry }}"
    tag: "spring-petclinic-vets-service-{{ .Values.services.vets-service.tag }}"
    port: 8083
  genai-service:
    image: "{{ .Values.dockerRegistry }}"
    tag: "spring-petclinic-genai-service-{{ .Values.services.genai-service.tag }}"
    port: 8084
  api-gateway:
    image: "{{ .Values.dockerRegistry }}"
    tag: "spring-petclinic-api-gateway-{{ .Values.services.api-gateway.tag }}"
    port: 8080
    ingress:
      enabled: true
      host: "{{ .Values.services.api-gateway.ingress.host }}"
  admin-server:
    image: "{{ .Values.dockerRegistry }}"
    tag: "spring-petclinic-admin-server-{{ .Values.services.admin-server.tag }}"
    port: 9090
replicaCount: {{ .Values.replicaCount }}